# Generated by Django 4.2.7 on 2023-12-01 12:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0049_remove_criminalprofile_criminal_fir_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usernotificationpanel",
            name="noti_message",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="usernotificationpanel",
            name="Title",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
