# Generated by Django 4.2.7 on 2023-12-01 12:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0050_usernotificationpanel_noti_message_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="case_fir",
            name="case_status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("On Going", "On Going"),
                    ("Completed", "Completed"),
                    ("Rejected", "Rejected"),
                ],
                default="Pending",
                max_length=255,
            ),
        ),
    ]
