# Generated by Django 4.2.7 on 2023-12-01 15:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0051_alter_case_fir_case_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="adminprofile",
            name="roles",
            field=models.CharField(
                choices=[("Admin", "Admin"), ("User", "User")],
                default="Admin",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="roles",
            field=models.CharField(
                choices=[("Admin", "Admin"), ("User", "User")],
                default="Admin",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="case_fir",
            name="case_status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("On Going", "On Going"),
                    ("Completed", "Completed"),
                    ("Rejected", "Rejected"),
                    ("Accepted", "Accepted"),
                ],
                default="Pending",
                max_length=255,
            ),
        ),
    ]
