# Generated by Django 4.2.7 on 2023-12-02 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0052_adminprofile_roles_userprofile_roles_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FIR_CRIMINAL",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "case_related",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.case_fir",
                    ),
                ),
                (
                    "criminal_related",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="myapp.criminalprofile",
                    ),
                ),
            ],
        ),
    ]
