# Generated by Django 4.2.7 on 2023-12-02 12:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0053_fir_criminal"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="criminalprofile",
            name="criminal_crimes",
        ),
        migrations.AlterField(
            model_name="criminalprofile",
            name="criminal_firs",
            field=models.ManyToManyField(blank=True, null=True, to="myapp.case_fir"),
        ),
        migrations.AddField(
            model_name="criminalprofile",
            name="criminal_crimes",
            field=models.ManyToManyField(blank=True, null=True, to="myapp.crimetype"),
        ),
    ]
