# Generated by Django 4.2.7 on 2023-12-02 15:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0054_remove_criminalprofile_criminal_crimes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="criminalprofile",
            name="criminal_detail_address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
