# Generated by Django 4.2.7 on 2023-12-02 17:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0057_victiminfo_detail_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="physicalstructure",
            name="other_info",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
