# Generated by Django 4.2.7 on 2023-12-02 19:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0058_physicalstructure_other_info"),
    ]

    operations = [
        migrations.AlterField(
            model_name="criminalprofile",
            name="criminal_crimes",
            field=models.ManyToManyField(blank=True, to="myapp.crimetype"),
        ),
        migrations.AlterField(
            model_name="criminalprofile",
            name="criminal_firs",
            field=models.ManyToManyField(blank=True, to="myapp.case_fir"),
        ),
    ]
