# Generated by Django 4.2.6 on 2024-01-16 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0061_alter_emergency_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='TandC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Term', models.CharField(max_length=200)),
            ],
        ),
    ]
