# Generated by Django 4.2.6 on 2024-01-16 21:21

from django.db import migrations, models
import myapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0062_tandc'),
    ]

    operations = [
        migrations.CreateModel(
            name='IGPS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Igps', models.CharField(max_length=200)),
                ('Message', models.CharField(max_length=400)),
                ('From', models.CharField(max_length=300)),
                ('image', models.ImageField(blank=True, null=True, upload_to=myapp.models.filepath)),
            ],
        ),
    ]
